### PR TITLE
Fixed compatibility with Magento 1.9.3.2.

### PR DESCRIPTION
**Pull request by iamniels**
Without this fix no search results are shown.

### CODE REVIEW

**Comment by jhuebel** [comment]
Would really like to see this merged into the fheyer repo, since this repo is the one that most people come to first. It took the better part of a morning to choose between the various forks and finally settle on hgati's code. Unfortunately, hgati isn't accepting bug reports to his fork. So, "support" of the extension is fragmented between a working fork (hgati) and the original repo (fheyer).

**Comment by fheyer** [comment]
Ok, thanks for the insight.
I'm preparing a test system now and will integrate all relevant patches this week.

**Comment by fheyer** [comment]
First thing: i can't accept this pull request in total as the author makes some changes which are not related to making this extension compatible with Magento 1.9. For example hgati removes the modman config which makes no sense as some people like to use modman.
So i will split this up.

**Comment by fheyer** [comment]
Thanks @iamniels, i integrated your original bugfixing commit into my repo.
Search now works again on Magento 1.9.3.0 and later. Thank you!
I am closing this pull request as all other commits are additions of other features and the original topic "Fixed compatibility with Magento 1.9.3.2" is solved.
@hgati I would happily accept pull requests for the other features.

**Comment by fheyer** [comment]
Solved by commit 4e30b984a53d5523e410fb89f1a5fa819e3fc209

**Pull request closed without merging**
